import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", '500', '600', '700']
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"]
});


export const metadata: Metadata = {
  title: "Portfolio - Iroegbu",
  description: "Generated by create next app",
  icons:{
    icon:'/profile-img-2a.jpg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${ovo.className} w-[100vw] h-screen antialiased leading-8 overflow-x-hidden `}>
        <Toaster position="top-center"/>
        {children}
      </body>
    </html>
  );
}
